In [7]:
import numpy as np
import qlp.mds.transformation as transform


In [8]:
# evaluate the QUBO given binary vector b and return energy F
def eval_QUBO(Q, b):
    #F = np.dot(b, np.dot(Q, b) )
    F = np.einsum('i,ij,j',b,Q,b)
    return F

# Convert non-negative n-bit integer to n-bit binary representation and return numpy array
def int_to_bin(a, n):
    l = int(a).bit_length(); # length of binary conversion
    # Check that the bit length fits the b-bit representation
    if l > n:
        print(" <<Bit length exceeds repreesntation size>>")
        raise ValueError
    x = bin(int(a)); # binary converstion returns string x
    y =x[2:l+2] # store last l chars of x in y
    b = np.zeros(n);
    for i in range(len(y)):
    	b[n-l+i] = int(y[i]); # add the bits from smallest to largest in the last l slots
    return b

# Find argument that minimizes QUBO F(b) = b^T Q b and return as numpy array
def argmin_QUBO(Q):
    n = len(Q);
    bx = int_to_bin(0, n);
    Fx = eval_QUBO(Q, bx);
    result = []
    for a in range(2**n): # loop over all 2^n possibilities
        b = int_to_bin(a, n); 
        F = eval_QUBO(Q, b);
        #print('%s  %s' %(b,F))
        result.append([F,b])
        if F < Fx:
            Fx = F
            bx = b
    return bx,result

In [95]:
# Dwave assume Ising
h = np.array([-3.0, 10.5, 2.5, 6.0, 6.0])
J = np.array([[ 0,  0,  8, -4, -4],
     [ 0,  0,-16, -4, -4],
     [ 0,  0,  0,  0,  0],
     [ 0,  0,  0,  0,  0],
     [ 0,  0,  0,  0,  0]])

In [96]:
Q = transform.Ising_to_QUBO(J, h)
Q

array([[ -6.,   0.,  32., -16., -16.],
       [  0.,  69., -64., -16., -16.],
       [  0.,   0.,  21.,   0.,   0.],
       [  0.,   0.,   0.,  28.,   0.],
       [  0.,   0.,   0.,   0.,  28.]])

In [154]:
# DWave assume QUBO
Q = [[2.5, 0.0, 0.0, 8.0, -16.0], [0.0, 6.0, 0.0, -4.0, -4.0], [0.0, 0.0, 6.0, -4.0, -4.0], [0.0, 0.0, 0.0, -3.0, 0.0], [0.0, 0.0, 0.0, 0.0, 10.5]]
J, h, _ = transform.QUBO_to_Ising(Q)
print(J, h)

[[ 0.  0.  0.  2. -4.]
 [ 0.  0.  0. -1. -1.]
 [ 0.  0.  0. -1. -1.]
 [ 0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.]] [-0.75  1.    1.   -1.5  -0.75]


In [137]:
# Hand craft
Q = [[-3.0, 8.0, -4.0, -4.0], [0.0, -3.0, -4.0, -4.0], [0.0, 0.0, 6.0, 0.0], [0.0, 0.0, 0.0, 6.0]]

In [146]:
bx, result = argmin_QUBO(Q)

In [147]:
result.sort(key=lambda x: x[0])

In [148]:
result

[[-2.0, array([0., 0., 0., 1., 0.])],
 [-2.0, array([1., 0., 0., 0., 1.])],
 [-1.3333333333333321, array([1., 1., 1., 1., 1.])],
 [-0.6666666666666665, array([0., 0., 1., 1., 0.])],
 [-0.6666666666666665, array([0., 1., 0., 1., 0.])],
 [-0.6666666666666661, array([1., 0., 1., 0., 1.])],
 [-0.6666666666666661, array([1., 1., 0., 0., 1.])],
 [0.0, array([0., 0., 0., 0., 0.])],
 [8.881784197001252e-16, array([1., 0., 1., 1., 1.])],
 [8.881784197001252e-16, array([1., 1., 0., 1., 1.])],
 [0.6666666666666674, array([0., 1., 1., 1., 0.])],
 [0.6666666666666679, array([1., 1., 1., 0., 1.])],
 [1.333333333333334, array([1., 0., 0., 1., 1.])],
 [1.6666666666666667, array([1., 0., 0., 0., 0.])],
 [2.333333333333334, array([0., 1., 1., 1., 1.])],
 [3.666666666666667, array([0., 0., 1., 1., 1.])],
 [3.666666666666667, array([0., 1., 0., 1., 1.])],
 [4.0, array([0., 0., 1., 0., 0.])],
 [4.0, array([0., 1., 0., 0., 0.])],
 [5.0, array([0., 0., 0., 1., 1.])],
 [5.0, array([1., 0., 0., 1., 0.])],
 [5.